const countries = [
  {
    value: 'Mongolia',
    label: 'Mongolia',
  },
];

const provinces = [
  {
    value: 'Ulaanbaatar',
    label: 'Ulaanbaatar',
  },
  {
    value: 'Arkhangai',
    label: 'Arkhangai',
  },
  {
    value: 'Bayankhongor',
    label: 'Bayankhongor',
  },
  {
    value: 'Bayan-Ulgii',
    label: 'Bayan-Ulgii',
  },
  {
    value: 'Bulgan',
    label: 'Bulgan',
  },
  {
    value: 'Darkhan-Uul',
    label: 'Darkhan-Uul',
  },
  {
    value: 'Dornod',
    label: 'Dornod',
  },
  {
    value: 'Dornogovi',
    label: 'Dornogovi',
  },
  {
    value: 'Dundgovi',
    label: 'Dundgovi',
  },
  {
    value: 'Govi-Altai',
    label: 'Govi-Altai',
  },
  {
    value: 'Govisümber',
    label: 'Govisümber',
  },
  {
    value: 'Khentii',
    label: 'Khentii',
  },
  {
    value: 'Khovd',
    label: 'Khovd',
  },
  {
    value: 'Khuvsgul',
    label: 'Khuvsgul',
  },
  {
    value: 'Orkhon',
    label: 'Orkhon',
  },
  {
    value: 'Selenge',
    label: 'Selenge',
  },
  {
    value: 'Sükhbaatar',
    label: 'Sükhbaatar',
  },
  {
    value: 'Tuv',
    label: 'Tuv',
  },
  {
    value: 'Umnugovi',
    label: 'Umnugovi',
  },
  {
    value: 'Uvs',
    label: 'Uvs',
  },
  {
    value: 'Uvurkhangai',
    label: 'Uvurkhangai',
  },
  {
    value: 'Zavkhan',
    label: 'Zavkhan',
  },
];

const discricts = [
  [
    'Baganuur',
    'Bayangol',
    'Bayanzürkh',
    'Chingeltei',
    'Khan Uul',
    'Nalaikh',
    'Songino Khairkhan',
    'Sükhbaatar',
  ],
  [
    'Battsengel',
    'Bulgan',
    'Chuluut',
    'Erdenebulgan',
    'Erdenemandal',
    'Ikh-Tamir',
    'Jargalant',
    'Khairkhan',
    'Khangai',
    'Khashaat',
    'Khotont',
    'Ögii nuur',
    'Ölziit',
    'Öndör-Ulaan',
    'Tariat',
    'Tüvshrüülekh',
    'Tsakhir',
    'Tsenkher',
    'Tsetserleg',
  ],
  [
    'Baatsagaan',
    'Bayan-Öndör',
    'Bayan-Ovoo',
    'Bayanbulag',
    'Bayangovi',
    'Bayankhongor',
    'Bayanlig',
    'Bayantsagaan',
    'Bogd',
    'Bömbögör',
    'Buutsagaan',
    'Erdenetsogt',
    'Galuut',
    'Gurvanbulag',
    'Jargalant',
    'Jinst',
    'Khüreemaral',
    'Ölziit',
    'Shinejinst',
    'Zag',
  ],
  [
    'Altai',
    'Altantsögts',
    'Bayannuur',
    'Bugat',
    'Bulgan',
    'Buyant',
    'Delüün',
    'Nogoonnuur',
    'Ölgii',
    'Sagsai',
    'Tolbo',
    'Tsagaannuur',
    'Tsengel',
    'Ulaankhus',
  ],
  [
    'Bayan-Agt',
    'Bayannuur',
    'Bugat',
    'Bulgan',
    'Büregkhangai',
    'Dashinchilen',
    'Gurvanbulag',
    'Khangal',
    'Khishig-Öndör',
    'Khutag-Öndör',
    'Mogod',
    'Orkhon',
    'Rashaant',
    'Saikhan',
    'Selenge',
    'Teshig',
  ],
  ['Darkhan', 'Khongor', 'Orkhon', 'Sharyngol'],
  [
    'Bayandun',
    'Bayantümen',
    'Bayan-Uul',
    'Bulgan',
    'Choibalsan',
    'Chuluunkhoroot (Ereentsav)',
    'Dashbalbar',
    'Gurvanzagal',
    'Khalkhgol',
    'Kherlen',
    'Khölönbuir',
    'Matad',
    'Sergelen',
    'Tsagaan-Ovoo',
  ],
  [
    'Airag',
    'Altanshiree',
    'Dalanjargalan',
    'Delgerekh',
    'Erdene',
    'Ikhkhet',
    'Khatanbulag',
    'Khövsgöl',
    'Mandakh',
    'Örgön',
    'Saikhandulaan',
    'Sainshand',
    'Ulaanbadrakh',
    'Zamyn-Üüd',
  ],
  [
    'Adaatsag',
    'Bayanjargalan',
    'Delgerkhangai',
    'Delgertsogt',
    'Deren',
    'Erdenedalai',
    'Govi-Ugtaal',
    'Gurvansaikhan',
    'Khuld',
    'Luus',
    'Ölziit',
    'Öndörshil',
    'Saikhan-Ovoo',
    'Saintsagaan',
    'Tsagaandelger',
  ],
  [
    'Altai',
    'Bayan-Uul',
    'Biger',
    'Bugat',
    'Chandmani',
    'Darvi',
    'Delger',
    'Erdene',
    'Khaliun',
    'Khökh morit',
    'Jargalan',
    'Sharga',
    'Taishir',
    'Tögrög',
    'Tonkhil',
    'Tseel',
    'Tsogt',
    'Yesönbulag',
  ],
  ['Bayantal', 'Shiveegovi', 'Sümber (Choir)'],
  [
    'Batnorov',
    'Batshireet',
    'Bayan-Adarga',
    'Bayankhutag',
    'Bayanmönkh',
    'Bayan-Ovoo',
    'Binder',
    'Dadal',
    'Darkhan',
    'Delgerkhaan',
    'Galshar',
    'Jargaltkhaan',
    'Kherlen',
    'Mörön',
    'Norovlin',
    'Ömnödelger',
    'Tsenkhermandal',
  ],
  [
    'Altai',
    'Bulgan',
    'Buyant',
    'Chandmani',
    'Darvi',
    'Dörgön',
    'Duut',
    'Erdenebüren',
    'Jargalant',
    'Khovd',
    'Mankhan',
    'Mönkhkhairkhan	',
    'Möst',
    'Myangad',
    'Tsetseg',
    'Üyench',
    'Zereg',
  ],
  [
    'Alag-Erdene (Khatgal)',
    'Arbulag',
    'Bayanzürkh',
    'Bürentogtokh',
    'Chandmani-Öndör',
    'Erdenebulgan',
    'Galt',
    'Ikh-Uul',
    'Jargalant',
    'Khankh',
    'Mörön',
    'Rashaant',
    'Renchinlkhümbe',
    'Shine-Ider',
    'Tarialan',
    'Tömörbulag',
    'Tosontsengel',
    'Tsagaannuur',
    'Tsagaan-Uul',
    'Tsagaan-Üür',
    'Tsetserleg',
    'Tünel',
    'Ulaan-Uul',
  ],
  ['Bayan-Öndör*', 'Jargalant'],
  [
    'Altanbulag',
    'Baruunbüren',
    'Bayangol',
    'Javkhlant',
    'Khüder',
    'Khushaat',
    'Mandal',
    'Orkhon',
    'Orkhontuul',
    'Sant',
    'Saikhan',
    'Shaamar',
    'Sükhbaatar',
    'Tsagaannuur',
    'Tüshig',
    'Yeröö',
    'Züünbüren',
  ],
  [
    'Asgat',
    'Baruun-Urt',
    'Bayandelger',
    'Dariganga',
    'Erdenetsagaan',
    'Halzan',
    'Mönhhaan',
    'Naran',
    'Ongon',
    'Sükhbaatar',
    'Tümentsogt',
    'Tüvshinshiree',
    'Uulbayan',
  ],
  [
    'Altanbulag',
    'Argalant',
    'Arkhust',
    'Batsümber',
    'Bayan',
    'Bayan-Önjüül',
    'Bayanchandmani',
    'Bayandelger',
    'Bayanjargalan',
    'Bayankhangai',
    'Bayantsagaan',
    'Bayantsogt',
    'Bornuur',
    'Büren',
    'Delgerkhaan',
    'Erdene',
    'Erdenesant',
    'Jargalant',
    'Lün',
    'Möngönmorit',
    'Öndörshireet',
    'Sergelen',
    'Sümber',
    'Tseel',
    'Ugtaal',
    'Zaamar',
    'Zuunmod',
  ],
  [
    'Bayan-Ovoo',
    'Bayandalai',
    'Bulgan',
    'Dalanzadgad',
    'Gurvan tes',
    'Khanbogd',
    'Khan khongor',
    'Khürmen',
    'Mandal-Ovoo',
    'Manlai',
    'Nomgon',
    'Noyon',
    'Sevrei',
    'Tsogt-Ovoo',
    'Tsogttsetsii',
  ],
  [
    'Baruunturuun',
    'Bökhmörön',
    'Davst',
    'Khovd',
    'Khyargas',
    'Malchin',
    'Naranbulag',
    'Ölgii',
    'Ömnögovi',
    'Öndörkhangai',
    'Sagil',
    'Tarialan',
    'Tes',
    'Tsagaankhairkhan',
    'Türgen',
    'Ulaangom',
    'Zavkhan',
    'Züüngovi',
    'Züünkhangai',
  ],
  [
    'Arvaikheer',
    'Baruun Bayan-Ulaan',
    'Bat-Ölzii',
    'Bayan-Öndör',
    'Bayangol',
    'Bogd',
    'Bürd',
    'Guchin-Us',
    'Khairkhandulaan',
    'Kharkhorin',
    'Khujirt',
    'Nariinteel',
    'Ölziit',
    'Sant',
    'Taragt',
    'Tögrög',
    'Uyanga',
    'Yesönzüil',
    'Züünbayan-Ulaan',
  ],
  [
    'Aldarkhaan',
    'Asgat',
    'Bayankhairhan',
    'Bayantes',
    'Dörvöljin',
    'Erdenekhairkhan',
    'Ider',
    'Ikh-Uul',
    'Nömrög',
    'Otgon',
    'Santmargats',
    'Shilüüstei',
    'Songino',
    'Telmen',
    'Tes',
    'Tosontsengel',
    'Tsagaanchuluut',
    'Tsagaankhairkhan',
    'Tsetsen-Uul',
    'Tüdevtei',
    'Uliastai',
    'Urgamal',
    'Yaruu',
    'Zavkhanmandal',
  ],
];

export { countries, provinces, discricts };
